### ISSUE TITLE
Issues with bib file on website - seem to be generated from JSON found here

### ISSUE THREAD

**Issue by jeanfrancisroy** [JmlrOrg/v16#1]
The bib file (and info JSON) of Germain et al.'s paper is wrong.

http://jmlr.org/papers/v16/germain15a.bib

In there, "Alexandre Lacasse"'s  and "Mario Marchand"'s name are wrong. It looks like some data processing messed up with the letters "and", present in both names.

The bib file in this repo seems correct (https://github.com/JmlrOrg/v16/blob/master/germain15a/germain15a.bib) but we can see the error in the info JSON file :
```
"authors": [
        "Pascal Germain",
        "Alex",
        "re Lacasse",
        "Francois Laviolette",
        "Mario March",
        "",
        "Jean-Francis Roy"
    ],
`
.

**Comment by fabianp** [comment]
Thanks for the report. Its now fixed and will be online shoftly
